import NavAdmin from "@/app/components/admin/navbar/NavAdmin";
import SideBar from "@/app/components/admin/sideBar/SideBar"
import "bootstrap/dist/css/bootstrap.min.css";
import "../../styles/admin/layout.css"


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    
      <body style={{margin:"0"}}>
      <div style={{display:"flex"}}>
        <NavAdmin />
        <SideBar class="lytSide" />
      {children}
      </div>
      </body>
    </html>
  )
}
