import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import Navbar from "./components/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getCategories(){
  const res = await import("./api/categorie/getCategoriesNoQuery/route");

  const categories = await (await res.GET()).json();

  return categories.data;
}

export default async function RootLayout({ children }) {

  const categories = await getCategories();


  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar allArticles={categories} />
      {children}
      </body>
    </html>
  );
}
